### ISSUE TITLE
how should i set cluster as there is no default cluster

### ISSUE THREAD

**Issue by virtouso** [pusher/pusher-websocket-dotnet#67]
i cant see any property to set cluster as result of server says did you forgot to set cluster 4001 message.

**Comment by damdo** [comment]
Hey @virtouso, you can set the `Cluster` string in the `PusherOptions` at `new Pusher()` object instantiation like so:
e.g
```c#
_pusher = new Pusher("APP_KEY", new PusherOptions()
{
    Cluster = "eu"
});
```

**Comment by virtouso** [comment]
@damdo  another problem is i cant use it in unity3d. as unity3d does not support nuget. i have to manullay find dll and put it in unity3d. when i use the dll file in assets i receive this error:


> Assembly 'Assets/PusherClient.dll' will not be loaded due to errors:
> Unable to resolve reference 'WebSocket4Net'. Is the assembly missing or incompatible with the current platform?
> Reference validation can be disabled in the Plugin Inspector.
> Unable to resolve reference 'SuperSocket.ClientEngine'. Is the assembly missing or incompatible with the current platform?
> Reference validation can be disabled in the Plugin Inspector.

i tested this on both android and windows target platform. is this realy tested on unity3d?

**Comment by damdo** [comment]
Hey @virtouso I'm closing this issue since it is related to how to set the `Cluster` (We will make it clearer and overall improve the documentation of this in the next period).

Could you please move [this comment](https://github.com/pusher/pusher-websocket-dotnet/issues/67#issuecomment-520410327) about the Unity integration under the #65 issue? I'd like to gather all the issues related to Unity there since I'd like to properly reply to them given that I recently worked on improving the Unity integration and I would like to share the results with you, there. Thank you
